name: Java Ant CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Java Ant
      run: sudo apt-get update && sudo apt-get -y install ant

    - name: Compile Java
      run: ant compile

    - name: Run Java
      run: ant run
